@startuml

hide footbox
title Foot Box removed

box "PIONEER" #LightBlue
actor Rebecca
database CUH 
collections "Co-recruited \n PIONEER IDs"
collections "Collated \n PIONEER PBCP \n database"
end box

box "Stats" #Lemon
actor Jerome
database "PIONEER Central Database" as pcdb
collections "PIONEER subset"
collections "PIONEER Pseudo-IDs"
collections "Pseudonymised \n PIONEER subset"
end box

box "PBCP" #LightGreen
actor Karen
database PBCP
end box


== Defining study patient subset ==

create "Co-recruited \n PIONEER IDs"
Rebecca -> "Co-recruited \n PIONEER IDs": Balance numbers across trial arms

pcdb -> Jerome: Parameters for analysis extracted

Karen -> Karen: Cross-reference PIONEER/PBCP Trial IDs
Karen -> Jerome: List of paired PBCP/PIONEER Trial IDs

create "PIONEER subset"
Jerome -> "PIONEER subset": Collate clinicopathological data with \n true Trial IDs (PIONEER & PBCP)

== Assign PIONEER pseudonyms ==
create "PIONEER Pseudo-IDs"
Jerome -> "PIONEER Pseudo-IDs" : Ascribe pseudonyms for \n PIONEER Trial IDs
Jerome -> "PIONEER Pseudo-IDs": Ascribe pseudonyms for \n PIONEER Treatment Arms
Jerome -> Karen: Share list of PIONEER Pseudo-IDs \n with corresponding PBCP ID

== Pseudonymised database generation ==
create "Pseudonymised \n PIONEER subset"
Jerome -> "Pseudonymised \n PIONEER subset": Jerome removes true Trial IDs (PIONEER & PBCP)
pcdb -> "Pseudonymised \n PIONEER subset":
note left: Ki67 end of treatment data added
"Pseudonymised \n PIONEER subset" -> Rebecca: Jerome shares pseudonymised database

== PBCP data re-labelling ==
PBCP -> Karen: Required PBCP data \n RNA seq \n Mutation calls \n SVs etc 
Karen -> Karen: Re-label PBCP data objects \n with PIONEER Pseudo-IDs

== Integration of data ==

Karen -> Rebecca: Share PBCP data with  PBCP IDs \n substituted for PIONEER pseudonyms
create "Collated \n PIONEER PBCP \n database"
Rebecca -> "Collated \n PIONEER PBCP \n database": Integrate Pseudonymised \n PIONEER subset \n and PBCP data to form \n dataset for analysis

@enduml
